language: python
services:
  - postgresql
  - memcached

python:
  - "3.6"

env:
  global:
    - DJANGO_SETTINGS_MODULE=estoudebike.settings.travis
    - PYTHONPATH=.

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libpq-dev

install:
  - pip install -r requirements.txt

script:
  - cd src/
  - pytest --cov=estacionamento --cov=bike_auth --cov=api
  - flake8 --ignore=E501 bike_auth/ estacionamento/ api/
