# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 19:24
from __future__ import unicode_literals

from django.db import migrations

from django.contrib.postgres.operations import CreateExtension


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        CreateExtension('postgis'),
    ]
