# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 20:17
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bike_auth', '0001_initial'),
        ('estacionamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('avaliacao', models.IntegerField(default=0)),
                ('local', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='estacionamento/fotos')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas', to='bike_auth.Token')),
            ],
        ),
    ]
